# Generate db.go from db.json downloaded nodejs mime-db project.
# NOTE: Autogenerated db.go needs to be vet proofed. \
#	Manually edit json -> JSON for all variable names
all: download gen-db

# Download db.json from NodeJS's mime-db project. It is under MIT license.
download:
	@mkdir -p ./shared/data
	@wget -nv -q https://cdn.rawgit.com/jshttp/mime-db/master/db.json -O shared/data/db.json


# After generating db.go, clean up downloaded db.json.
gen-db: download
	@go run -race ./cmd/gen-mimedb/main.go ./shared/data/db.json > ./pkg/db.go
	@echo Generated \"./pkg/db.go\".

example:
	@go run -race example/main.go

clean:
	@rm -fR ./dist/*
	@rm -fR ./bin/*
	@rm -f ./shared/data/db.json
	@rm -rf ./shared/data